[package]
name = "quickserving-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
quickserving-core = { git = "https://github.com/Baguuc/quickserving-core.git" }
clap = { version = "4.5.4", features = ["derive"] }
simple_logger = "5.0.0"
log = "0.4.22"